name: Test NordVPN Connection

on:
  push:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes
  workflow_dispatch:

jobs:
  test-nordvpn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install NordVPN CLI
        run: |
          wget -qO - https://downloads.nordcdn.com/apps/linux/install.sh | sudo bash
          sudo groupadd nordvpn || true
          sudo usermod -aG nordvpn $USER

      - name: Log in to NordVPN using Token
        run: |
          sudo nordvpn login --token "${{ secrets.NORDVPN_TOKEN }}"
          sudo nordvpn set technology nordlynx

      - name: Connect to NordVPN
        run: |
          sudo nordvpn connect
          sleep 10 # Wait for connection to establish

      - name: Get and Print IP Address
        run: |
          curl -s https://api64.ipify.org
